version: 2.1

executors:
  tools-executor:
    working_directory: ~/kee-frame
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.3.1020-node-browsers

jobs:
  build:
    executor: tools-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - kee-frame-deps-{{ checksum "deps.edn" }}
          - kee-frame-deps-
      - run: clojure -T:build jar
      - save_cache:
          paths:
            - ~/.m2
          key:  kee-frame-deps-{{ checksum "deps.edn" }}

  deploy:
    executor: tools-executor
    steps:
      - checkout
      - restore_cache:
          keys:
          - kee-frame-deps-{{ checksum "deps.edn" }}
          - kee-frame-deps-
      - run: clojure -T:build maybe-deploy
      - save_cache:
          paths:
            - ~/.m2
          key:  kee-frame-deps-{{ checksum "deps.edn" }}

workflows:
  build-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /Release-.*/
          context:
            - CLOJARS_DEPLOY
